-- age_group definition

CREATE TABLE "age_group" (
    [AGE_GROUP_CODE] TEXT,
    [UPPER_AGE] TEXT,
    [LOWER_AGE] TEXT,
    PRIMARY KEY ([AGE_GROUP_CODE])
);


-- customer_contact definition

CREATE TABLE "customer_contact" (
    [CUSTOMER_CONTACT_CODE] TEXT,
    [CUSTOMER_SITE_CODE] TEXT,
    [FIRST_NAME] TEXT,
    [LAST_NAME] TEXT,
    [JOB_POSITION_EN] TEXT,
    [EXTENSION] TEXT,
    [FAX] TEXT,
    [E_MAIL] TEXT,
    [GENDER] TEXT,
    PRIMARY KEY ([CUSTOMER_CONTACT_CODE])
);


-- customer_segment definition

CREATE TABLE "customer_segment" (
    [SEGMENT_CODE] TEXT,
    [LANGUAGE] TEXT,
    [SEGMENT_NAME] TEXT,
    [SEGMENT_DESCRIPTION] TEXT,
    PRIMARY KEY ([SEGMENT_CODE])
);


-- customer_type definition

CREATE TABLE "customer_type" (
    [CUSTOMER_TYPE_CODE] TEXT,
    [CUSTOMER_TYPE_EN] TEXT,
    PRIMARY KEY ([CUSTOMER_TYPE_CODE])
);


-- sales_territory definition

CREATE TABLE "sales_territory" (
    [SALES_TERRITORY_CODE] TEXT,
    [TERRITORY_NAME_EN] TEXT,
    PRIMARY KEY ([SALES_TERRITORY_CODE])
);


-- crm_country definition

CREATE TABLE "crm_country" (
	"COUNTRY_CODE"	TEXT,
	"COUNTRY_EN"	TEXT,
	"FLAG_IMAGE"	TEXT,
	"SALES_TERRITORY_CODE"	TEXT,
	PRIMARY KEY("COUNTRY_CODE"),
	FOREIGN KEY("SALES_TERRITORY_CODE") REFERENCES "sales_territory"("SALES_TERRITORY_CODE")
);


-- customer_headquarters definition

CREATE TABLE "customer_headquarters" (
	"CUSTOMER_CODEMR"	TEXT,
	"CUSTOMER_NAME"	TEXT,
	"ADDRESS1"	TEXT,
	"ADDRESS2"	TEXT,
	"CITY"	TEXT,
	"REGION"	TEXT,
	"POSTAL_ZONE"	TEXT,
	"COUNTRY_CODE"	TEXT,
	"PHONE"	TEXT,
	"FAX"	TEXT,
	"SEGMENT_CODE"	TEXT,
	PRIMARY KEY("CUSTOMER_CODEMR"),
	FOREIGN KEY("SEGMENT_CODE") REFERENCES "customer_segment"("SEGMENT_CODE")
);


-- sales_demographic definition

CREATE TABLE "sales_demographic" (
	"DEMOGRAPHIC_CODE"	TEXT,
	"CUSTOMER_CODEMR"	TEXT,
	"AGE_GROUP_CODE"	TEXT,
	"SALES_PERCENT"	TEXT,
	FOREIGN KEY("AGE_GROUP_CODE") REFERENCES "age_group"("AGE_GROUP_CODE") ON DELETE CASCADE,
	FOREIGN KEY("CUSTOMER_CODEMR") REFERENCES "customer_headquarters"("CUSTOMER_CODEMR") ON DELETE CASCADE
);


-- customer definition

CREATE TABLE "customer" (
	"CUSTOMER_CODE"	TEXT,
	"CUSTOMER_CODEMR"	TEXT,
	"COMPANY_NAME"	TEXT,
	"CUSTOMER_TYPE_CODE"	TEXT,
	PRIMARY KEY("CUSTOMER_CODE"),
	FOREIGN KEY("CUSTOMER_CODEMR") REFERENCES "customer_headquarters"("CUSTOMER_CODEMR"),
	FOREIGN KEY("CUSTOMER_TYPE_CODE") REFERENCES "customer_type"("CUSTOMER_TYPE_CODE")
);


-- customer_store definition

CREATE TABLE "customer_store" (
	"CUSTOMER_SITE_CODE"	TEXT,
	"CUSTOMER_CODE"	TEXT,
	"STREET"	TEXT,
	"ADDITION"	TEXT,
	"CITY"	TEXT,
	"STATE"	TEXT,
	"ZIPCODE"	TEXT,
	"COUNTRY_CODE"	TEXT,
	"ACTIVE_INDICATOR"	TEXT,
	PRIMARY KEY("CUSTOMER_SITE_CODE"),
	FOREIGN KEY("COUNTRY_CODE") REFERENCES "crm_country"("COUNTRY_CODE"),
	FOREIGN KEY("CUSTOMER_CODE") REFERENCES "customer"("CUSTOMER_CODE")
);
