-- Dim_Customer definition

CREATE TABLE "Dim_Customer" (
"RETAILER_SITE_CODE" TEXT,
  "RETAILER_CODE" TEXT,
  "CITY" TEXT,
  "REGION" TEXT,
  "COUNTRY_CODE" TEXT,
  "COUNTRY" TEXT
);


-- Dim_Date definition

CREATE TABLE "Dim_Date" (
"DATE" TIMESTAMP,
  "DATE_ID" INTEGER,
  "YEAR" INTEGER,
  "MONTH" INTEGER,
  "DAY" INTEGER,
  "DATE_STR" TEXT
);


-- Dim_Product definition

CREATE TABLE "Dim_Product" (
"PRODUCT_NUMBER" TEXT,
  "PRODUCT_NAME" TEXT,
  "PRODUCT_TYPE_CODE" TEXT,
  "PRODUCT_TYPE_EN" TEXT,
  "PRODUCT_LINE_CODE" TEXT,
  "PRODUCT_LINE_EN" TEXT,
  "PRODUCTION_COST" TEXT,
  "MARGIN" TEXT
);


-- Dim_Return_Reason definition

CREATE TABLE "Dim_Return_Reason" (
"RETURN_REASON_CODE" TEXT,
  "RETURN_DESCRIPTION_EN" TEXT
);


-- Dim_Staff definition

CREATE TABLE "Dim_Staff" (
"SALES_STAFF_CODE" TEXT,
  "FIRST_NAME" TEXT,
  "LAST_NAME" TEXT,
  "POSITION_EN" TEXT,
  "BRANCH_REGION" TEXT
);


-- Fact_Returns definition

CREATE TABLE "Fact_Returns" (
"RETURN_CODE" TEXT,
  "RETURN_DATE" TIMESTAMP,
  "ORDER_DETAIL_CODE" TEXT,
  "RETURN_REASON_CODE" TEXT,
  "RETURN_QUANTITY" TEXT,
  "PRODUCT_NUMBER" TEXT,
  "RETAILER_SITE_CODE" TEXT,
  "DATE_ID" INTEGER
);


-- Fact_Sales definition

CREATE TABLE "Fact_Sales" (
"ORDER_DATE" TIMESTAMP,
  "ORDER_DETAIL_CODE" TEXT,
  "ORDER_NUMBER" TEXT,
  "PRODUCT_NUMBER" TEXT,
  "RETAILER_SITE_CODE" TEXT,
  "SALES_STAFF_CODE" TEXT,
  "QUANTITY" TEXT,
  "UNIT_COST" TEXT,
  "UNIT_SALE_PRICE" TEXT,
  "REVENUE" REAL,
  "TOTAL_COST" REAL,
  "DATE_ID" INTEGER
);


-- Fact_Sales_Targets definition

CREATE TABLE "Fact_Sales_Targets" (
"DATE_ID" INTEGER,
  "SALES_STAFF_CODE" INTEGER,
  "PRODUCT_NUMBER" INTEGER,
  "RETAILER_CODE" INTEGER,
  "SALES_TARGET" INTEGER
);
