-- country definition

CREATE TABLE "country" (
    [COUNTRY_CODE] TEXT,
    [COUNTRY] TEXT,
    [LANGUAGE] TEXT,
    [CURRENCY_NAME] TEXT,
    PRIMARY KEY ([COUNTRY_CODE])
);


-- order_method definition

CREATE TABLE "order_method" (
    [ORDER_METHOD_CODE] TEXT,
    [ORDER_METHOD_EN] TEXT,
    PRIMARY KEY ([ORDER_METHOD_CODE])
);


-- product_line definition

CREATE TABLE "product_line" (
    [PRODUCT_LINE_CODE] TEXT,
    [PRODUCT_LINE_EN] TEXT,
    PRIMARY KEY ([PRODUCT_LINE_CODE])
);


-- retailer_site definition

CREATE TABLE "retailer_site" (
    [RETAILER_SITE_CODE] TEXT,
    [RETAILER_CODE] TEXT,
    [ADDRESS1] TEXT,
    [ADDRESS2] TEXT,
    [CITY] TEXT,
    [REGION] TEXT,
    [POSTAL_ZONE] TEXT,
    [COUNTRY_CODE] TEXT,
    [ACTIVE_INDICATOR] TEXT,
    PRIMARY KEY ([RETAILER_SITE_CODE])
);


-- return_reason definition

CREATE TABLE "return_reason" (
    [RETURN_REASON_CODE] TEXT,
    [RETURN_DESCRIPTION_EN] TEXT,
    PRIMARY KEY ([RETURN_REASON_CODE])
);


-- product_type definition

CREATE TABLE "product_type" (
    [PRODUCT_TYPE_CODE] TEXT,
    [PRODUCT_LINE_CODE] TEXT,
    [PRODUCT_TYPE_EN] TEXT,
    PRIMARY KEY ([PRODUCT_TYPE_CODE]),
    FOREIGN KEY ([PRODUCT_LINE_CODE]) REFERENCES [product_line]([PRODUCT_LINE_CODE]) ON DELETE RESTRICT
);


-- sales_branch definition

CREATE TABLE "sales_branch" (
	"SALES_BRANCH_CODE"	TEXT,
	"ADDRESS1"	TEXT,
	"ADDRESS2"	TEXT,
	"CITY"	TEXT,
	"REGION"	TEXT,
	"POSTAL_ZONE"	TEXT,
	"COUNTRY_CODE"	TEXT,
	PRIMARY KEY("SALES_BRANCH_CODE"),
	FOREIGN KEY("COUNTRY_CODE") REFERENCES "country"("COUNTRY_CODE") ON DELETE RESTRICT
);


-- sales_staff definition

CREATE TABLE "sales_staff" (
    [SALES_STAFF_CODE] TEXT,
    [FIRST_NAME] TEXT,
    [LAST_NAME] TEXT,
    [POSITION_EN] TEXT,
    [WORK_PHONE] TEXT,
    [EXTENSION] TEXT,
    [FAX] TEXT,
    [EMAIL] TEXT,
    [DATE_HIRED] TEXT,
    [SALES_BRANCH_CODE] TEXT,
    PRIMARY KEY ([SALES_STAFF_CODE]),
    FOREIGN KEY ([SALES_BRANCH_CODE]) REFERENCES [sales_branch]([SALES_BRANCH_CODE]) ON DELETE RESTRICT
);


-- order_header definition

CREATE TABLE "order_header" (
    [ORDER_NUMBER] TEXT,
    [RETAILER_NAME] TEXT,
    [RETAILER_SITE_CODE] TEXT,
    [RETAILER_CONTACT_CODE] TEXT,
    [SALES_STAFF_CODE] TEXT,
    [SALES_BRANCH_CODE] TEXT,
    [ORDER_DATE] TEXT,
    [ORDER_METHOD_CODE] TEXT,
    PRIMARY KEY ([ORDER_NUMBER]),
    FOREIGN KEY ([ORDER_METHOD_CODE]) REFERENCES [order_method]([ORDER_METHOD_CODE]) ON DELETE RESTRICT,
    FOREIGN KEY ([RETAILER_SITE_CODE]) REFERENCES [retailer_site]([RETAILER_SITE_CODE]) ON DELETE RESTRICT,
    FOREIGN KEY ([SALES_BRANCH_CODE]) REFERENCES [sales_branch]([SALES_BRANCH_CODE]) ON DELETE RESTRICT,
    FOREIGN KEY ([SALES_STAFF_CODE]) REFERENCES [sales_staff]([SALES_STAFF_CODE]) ON DELETE RESTRICT
);


-- product definition

CREATE TABLE "product" (
    [PRODUCT_NUMBER] TEXT,
    [INTRODUCTION_DATE] TEXT,
    [PRODUCT_TYPE_CODE] TEXT,
    [PRODUCTION_COST] TEXT,
    [MARGIN] TEXT,
    [PRODUCT_IMAGE] TEXT,
    [LANGUAGE] TEXT,
    [PRODUCT_NAME] TEXT,
    [DESCRIPTION] TEXT,
    PRIMARY KEY ([PRODUCT_NUMBER]),
    FOREIGN KEY ([PRODUCT_TYPE_CODE]) REFERENCES [product_type]([PRODUCT_TYPE_CODE]) ON DELETE RESTRICT
);


-- order_details definition

CREATE TABLE "order_details" (
    [ORDER_DETAIL_CODE] TEXT,
    [ORDER_NUMBER] TEXT,
    [PRODUCT_NUMBER] TEXT,
    [QUANTITY] TEXT,
    [UNIT_COST] TEXT,
    [UNIT_PRICE] TEXT,
    [UNIT_SALE_PRICE] TEXT,
    PRIMARY KEY ([ORDER_DETAIL_CODE]),
    FOREIGN KEY ([ORDER_NUMBER]) REFERENCES [order_header]([ORDER_NUMBER]) ON DELETE RESTRICT,
    FOREIGN KEY ([PRODUCT_NUMBER]) REFERENCES [product]([PRODUCT_NUMBER]) ON DELETE RESTRICT
);


-- returned_item definition

CREATE TABLE "returned_item" (
    [RETURN_CODE] TEXT,
    [RETURN_DATE] TEXT,
    [ORDER_DETAIL_CODE] TEXT,
    [RETURN_REASON_CODE] TEXT,
    [RETURN_QUANTITY] TEXT,
    PRIMARY KEY ([RETURN_CODE]),
    FOREIGN KEY ([ORDER_DETAIL_CODE]) REFERENCES [order_details]([ORDER_DETAIL_CODE]) ON DELETE RESTRICT,
    FOREIGN KEY ([RETURN_REASON_CODE]) REFERENCES [return_reason]([RETURN_REASON_CODE]) ON DELETE RESTRICT
);
