-- course definition

CREATE TABLE "course" (
    [COURSE_CODE] TEXT,
    [COURSE_DESCRIPTION] TEXT,
    PRIMARY KEY ([COURSE_CODE])
);


-- sales_office definition

CREATE TABLE "sales_office" (
    [SALES_OFFICE_CODE] TEXT,
    [STREET] TEXT,
    [ADDITION] TEXT,
    [CITY] TEXT,
    [REGION] TEXT,
    [ZIPCODE] TEXT,
    [COUNTRY_CODE] TEXT,
    PRIMARY KEY ([SALES_OFFICE_CODE])
);


-- satisfaction_type definition

CREATE TABLE "satisfaction_type" (
    [SATISFACTION_TYPE_CODE] TEXT,
    [SATISFACTION_TYPE_DESCRIPTION] TEXT,
    PRIMARY KEY ([SATISFACTION_TYPE_CODE])
);


-- sales_representative definition

CREATE TABLE "sales_representative" (
	"SALES_REPRESENTATIVE_CODE"	TEXT,
	"FIRST_NAME"	TEXT,
	"LAST_NAME"	TEXT,
	"POSITION_EN"	TEXT,
	"WORK_PHONE"	TEXT,
	"EXTENSION"	TEXT,
	"FAX"	TEXT,
	"EMAIL"	TEXT,
	"DATE_HIRED"	TEXT,
	"SALES_OFFICE_CODE"	TEXT,
	"MANAGER_CODE"	TEXT,
	PRIMARY KEY("SALES_REPRESENTATIVE_CODE"),
	FOREIGN KEY("MANAGER_CODE") REFERENCES "sales_representative"("SALES_REPRESENTATIVE_CODE"),
	FOREIGN KEY("SALES_OFFICE_CODE") REFERENCES "sales_office"("SALES_OFFICE_CODE")
);


-- satisfaction definition

CREATE TABLE "satisfaction" (
"YEAR" TEXT,
  "SALES_REPRESENTATIVE_CODE" TEXT,
  "SATISFACTION_TYPE_CODE" TEXT
,
  FOREIGN KEY ([SALES_REPRESENTATIVE_CODE]) REFERENCES [sales_representative]([SALES_REPRESENTATIVE_CODE]) ON DELETE CASCADE,
  FOREIGN KEY ([SATISFACTION_TYPE_CODE]) REFERENCES [satisfaction_type]([SATISFACTION_TYPE_CODE]) ON DELETE CASCADE
);


-- training definition

CREATE TABLE "training" (
"YEAR" TEXT,
  "SALES_REPRESENTATIVE_CODE" TEXT,
  "COURSE_CODE" TEXT
,
  FOREIGN KEY ([COURSE_CODE]) REFERENCES [course]([COURSE_CODE]) ON DELETE CASCADE,
  FOREIGN KEY ([SALES_REPRESENTATIVE_CODE]) REFERENCES [sales_representative]([SALES_REPRESENTATIVE_CODE]) ON DELETE CASCADE
);
